pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mfdaphne/problems.git']]])
                echo 'Checkout is successful'
            }
        }
        
        stage('Clean') {
            steps {
                dir('./priority-queue') {
                sh 'gradle clean'
                echo 'Cleaning successful'
                   }
            }
        }
        
         stage('Test') {
            steps {
                dir('./priority-queue') {
                sh 'gradle test'
                echo 'Testing successful'
                 }
            }
        }
        
         stage('Build') {
            steps {
                dir('./priority-queue') {
                sh 'gradle build'
                echo 'Building successful'
                 }
            }
        }
        
       
    }
}
